### ISSUE TITLE
The calculation of ML metrics is not quite appropriate.

### ISSUE THREAD

**Issue by echo840** [MMStar-Benchmark/MMStar#6]
Thank you very much for your great work, it has been very enlightening. However, I have some questions regarding the calculation of ML metrics .

Firstly, I believe it would be more appropriate to use the performance of LLMs in 2-shot scenarios, as indicated in Table 2, as the baseline in Table 3, Table 5 and Table 6. In 0-shot scenarios, some LLMs may not adhere to the answer paradigm or refuse to answer, resulting in extremely low LLM scores. This also leads to a higher likelihood of evaluating LVLMs that incorporate such LLMs as having more severe data leakage issues. 

For example, in the 0-shot scenario, Qwen-7B has an average score of 25.3 in Table 1, which is the lowest among all LLMs and approximately 10 points lower than LLMs of the similar size. It even performs worse than the smaller models, Phi2-2.7B and Qwen1.5-1.8B. Clearly, this does not align with the actual capabilities of Qwen-7B. However, in the 2-shot scenario, Qwen-7B achieves a score of 35.4, which is more consistent with the scores of other models of similar size. 

If we consider the 0-shot scenario as the baseline for data leakage, then Qwen-7B would have ML score of 10.1 in 2-shot compared to the 0-shot scenario while others are normally lower than 5, which indicates a significant data leakage issue, even though no actual data leakage occurs in this process. LLM has only learned how to correctly format the output of an answer rather than refusing to answer.

![image](https://github.com/MMStar-Benchmark/MMStar/assets/87795401/d63c2e65-974c-4be9-b7dc-fedd70728600)

In the table above, qwen7b has a 10.1 higher score in the 2-shot scenario compared to the 0-shot scenario, which is the highest. When using 0-shot as the baseline, both monkey-chat and Sphinx-X-MoE have an ML score of 14.2, indicating the highest likelihood of data leakage during multimodal training for both models. However, when using 2-shot as the standard, monkey-chat only has an ML score of 4.1 and Sphinx-X-MoE only has an ML score of 5, suggesting a low degree of data leakage.

Therefore, we have the reason to believe that the reason monkey-chat and Sphinx-X-MoE achieves the highest ML in 0-shot is more likely due to its ability to better follow instructions and generate answers that conform to the given format after multimodal training, rather than due to data leakage.

Moreover, I think it is also essential to further consider the possibility of refusing to answer in LVLM-text.

Overall, I think it's more appropriate to use the performance of LLMs in 2-shot scenarios, as indicated in Table 2, as the baseline in Table 3, Table5 and Table 6. Because in 0-shot scenarios, some LLMs may not adhere to the answer paradigm or refuse to answer, resulting in extremely low LLM scores. This is unfair for the subsequent calculation of ML.

Thank you again for your great work!

**Comment by xiaoachen98** [comment]
> Thank you very much for your great work, it has been very enlightening. However, I have some questions regarding the calculation of ML metrics .
> 
> Firstly, I believe it would be more appropriate to use the performance of LLMs in 2-shot scenarios, as indicated in Table 2, as the baseline in Table 3, Table 5 and Table 6. In 0-shot scenarios, some LLMs may not adhere to the answer paradigm or refuse to answer, resulting in extremely low LLM scores. This also leads to a higher likelihood of evaluating LVLMs that incorporate such LLMs as having more severe data leakage issues.
> 
> For example, in the 0-shot scenario, Qwen-7B has an average score of 25.3 in Table 1, which is the lowest among all LLMs and approximately 10 points lower than LLMs of the similar size. It even performs worse than the smaller models, Phi2-2.7B and Qwen1.5-1.8B. Clearly, this does not align with the actual capabilities of Qwen-7B. However, in the 2-shot scenario, Qwen-7B achieves a score of 35.4, which is more consistent with the scores of other models of similar size.
> 
> If we consider the 0-shot scenario as the baseline for data leakage, then Qwen-7B would have ML score of 10.1 compared to the 0-shot scenario while others are normally lower than 5, which indicates a significant data leakage issue, even though no actual data leakage occurs in this process. LLM has only learned how to correctly format the output of an answer rather than refusing to answer.
> 
> ![image](https://private-user-images.githubusercontent.com/87795401/320791326-d63c2e65-974c-4be9-b7dc-fedd70728600.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2NTg2OTYsIm5iZiI6MTcxMjY1ODM5NiwicGF0aCI6Ii84Nzc5NTQwMS8zMjA3OTEzMjYtZDYzYzJlNjUtOTc0Yy00YmU5LWI3ZGMtZmVkZDcwNzI4NjAwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA5VDEwMjYzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5MzEzNGY0NjZhZDBhM2M5M2U2OTdhYjVlNTczMGYyN2VlNWJhMTQyZGVmYTU3YWU3Y2YxZTE2ZDUxZTUzY2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0d6ZfsuqqynEuuk3EzkGi8TqrSBbPxI2yMSVl_uW7uc)
> 
> In the table above, qwen7b has a 10.1 higher score in the 2-shot scenario compared to the 0-shot scenario, which is the highest. When using 0-shot as the baseline, both monkey-chat and Sphinx-X-MoE have an ML score of 14.2, indicating the highest likelihood of data leakage during multimodal training for both models. However, when using 2-shot as the standard, monkey-chat only has an ML score of 4.1 and Sphinx-X-MoE only has an ML score of 5, suggesting a low degree of data leakage.
> 
> Therefore, we have the reason to believe that the reason monkey-chat and Sphinx-X-MoE achieves the highest ML in 0-shot is more likely due to its ability to better follow instructions and generate answers that conform to the given format after multimodal training, rather than due to data leakage.
> 
> Moreover, I think it is also essential to further consider the possibility of refusing to answer in LVLM-text.
> 
> Overall, I think it's more appropriate to use the performance of LLMs in 2-shot scenarios, as indicated in Table 2, as the baseline in Table 3, Table5 and Table 6. Because in 0-shot scenarios, some LLMs may not adhere to the answer paradigm or refuse to answer, resulting in extremely low LLM scores. This is unfair for the subsequent calculation of ML.
> 
> Thank you again for your great work!

Thanks for your valuable suggestion. We will consider your suggestions and update our paper in the next version.
